---

apiVersion: v1
kind: Service
metadata:
  name: postgress-service
  labels:
    name: postgress-service
    author: gow
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgress-app