---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    name: result-app
    author: gow

spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app
    spec:
      - name: myresultapp
        image: dockersamples/examplevotingapp_result
...